### ISSUE TITLE
Installation path cannot be provided in hubg

### ISSUE THREAD

**Issue by Ray-Hoo** [fr3nd/msxhub#17]
When you would like to install in a different path then the default, this is not possible using hubg. It would be useful when you choose for inStall that there is a question to which path before installing.

**Comment by fr3nd** [comment]
@ducasp I think that's for you ;)

**Comment by ducasp** [comment]
It should accept the same commands hub does, I'll look at it once I come
back from vacations, but if my memory serves me well, it should work. 🙂

Em qui, 30 de dez de 2021 07:49, Carles Amigó ***@***.***>
escreveu:

**Comment by ducasp** [comment]
@Ray-Hoo ,

MSX HUB package includes HUBG.TXT manual, and in there it describes:

```
There are two ways of overriding this behavior:

	- If you just want a given package to install in a different folder, keep 
	  SHIFT pressed while you press S or U, HUBG will ask you where you want to
	  install that package, just type it and hit enter. IMPORTANT: notice that
	  HUBG is, at this moment, able to create only ONE folder, so, let's say 
	  you want to install VI in C:\EDITORS\VI folder, if C:\EDITORS already
	  exists, it will work fine, if not, it won't work at all
	  
	- If you want to have a folder as a default place to install all packages,
	  you can set an environment variable with the name PROGSDIR, i.e.: at the
	  MSX-DOS2 prompt (or you can have this included in your autoexec.bat) you
	  type SET PROGSDIR=C:\HUBPACKS. When you install VI, for example, HUBG 
	  will install it in C:\HUBPACKS\VI. IMPORTANT: that folder MUST already
	  exists, otherwise it won't work at all
	  
And the coolest thing of all, don't worry if you install some packages at a non
default location and have others installed at default location. HUB and HUBG 
are smart enough to be able to uninstall or upgrade it at any time (just remind
that when upgrading, if PROGSDIR is not set or SHIFT is not pressed, it will
uninstall from the current location but then re-install it in the default 
location).
```

The holding SHIFT method is a replacement to the HUB.COM option to add an installation DIR after install (i.e.: hub install brunilda a:\games\brunilda , and since it uses the same base code as HUB.COM for that, it has the same limitation where it will be able to create only one folder (in that case, a:\games must already exist). Since individual packages installation are not given in command line for HUBG, it makes sense to have a "modifier" key when choosing to install a package.

The environment variable works exactly like with HUB.COM (idea is that users are free to use HUB or HUBG at will, and either one will understand whatever was installed or uninstalled by the other, so both share the same config file and behaviors).

I've tested both methods extensively prior to releasing HUBG, so I'm confident that this is not an issue. Let us know if you have tried both methods and had an issue with either one (or both).

@fr3nd , I recommend closing this issue, we can re-open it just in case Ray-Hoo tells us he tried those methods and had an issue with those, my understanding is that he was not aware of the shift key acting as a modifier to install/uninstall allowing to choose where to install the package.

**Comment by Ray-Hoo** [comment]
Issue can be closed. I didn't know the shift option. Works like a charm.
